import "./globals.css";

import NavbarComponent from "@/components/navbar/NavbarComponent";
import FooterComponent from "@/components/footer/FooterComponent";
import Title from "@/components/title/Title";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavbarComponent />
        <main>
          <Title />
          {children}
          <FooterComponent />
        </main>
      </body>
    </html>
  );
}
